### ISSUE TITLE
Link to PDF manual is broken

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#118]

**Comment by zickgraf** [comment]
Ah, I found the culprit: This is due to relelease-gap-package's new support for uploading multiple PDFs. Previously, there was only a single PDF which was named in the format "PACKAGE_NAME-VERSION.pdf", see for example https://github.com/homalg-project/FinSetsForCAP/releases/tag/v2023.01-04. Now that multiple PDFs are supported, the name from "PDFFile" in PackageInfo.g is chosen. There are some possible solutions all with pros and cons -> I will have to think about this.

**Comment by zickgraf** [comment]
And the date in the manual is broken, too :( I would like to use the upstream version of release-gap-package, but maybe this creates more problems than it solves.

**Comment by zickgraf** [comment]
Fixed by f4ce017a69d1a21eef42d88f0e4725d08dd7af4b. Note that this introduces a change on the gh-pages branch which also has to be committed and pushed.
