### ISSUE TITLE
header and footer in README.md

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#16]
The README.md does not render correctly here

https://homalg-project.github.io/SubcategoriesForCAP/

while it does there

https://homalg-project.github.io/LoopIntegrals/

Does this have to do with header/footer in the former?

**Comment by zickgraf** [comment]
> Does this have to do with header/footer in the former?

Yes, gh-pages/Jekyll seem to render the markdown using kramdown, which handles HTML comments in a different way than GitHub. There is an option to use GFM instead, can I use SubcategoriesForCAP to test this?

**Comment by zickgraf** [comment]
I have fixed this for SubcategoriesForCAP: https://github.com/homalg-project/SubcategoriesForCAP/commit/0509c8f9c10f465c76cd03b133a80be51d9fd11b

I have created a PR: https://github.com/homalg-project/SubcategoriesForCAP/commit/0509c8f9c10f465c76cd03b133a80be51d9fd11b

Unfortunately, `PackageJanitor` does not know about the `gh-pages` branch yet, so for now this has to be changed manually :-(

**Comment by zickgraf** [comment]
I have closed my PR https://github.com/gap-system/GitHubPagesForGAP/pull/20 since `GFM` cannot be used locally and other alternatives would be hard to maintain. However, I think we could still use `GFM` in our repos.

Do you always have the `gh-pages` branch checked out in a subdirectory called `gh-pages`? In this case, I can add a simple rule to PackageJanitor changing the `markdown` to `GFM` automatically.

**Comment by mohamed-barakat** [comment]
> I have closed my PR [gap-system/GitHubPagesForGAP#20](https://github.com/gap-system/GitHubPagesForGAP/pull/20) since `GFM` cannot be used locally and other alternatives would be hard to maintain. 

OK, I see.

> However, I think we could still use `GFM` in our repos. Do you always have the `gh-pages` branch checked out in a subdirectory called `gh-pages`? In this case, I can add a simple rule to PackageJanitor changing the `markdown` to `GFM` automatically.

Yes, I do :)
