### ISSUE TITLE
Is it possible to allow multiple spaces before or within comments?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#5]
Here is a use-case:
https://github.com/mohamed-barakat/SubcategoriesForCAP/blob/master/gap/SliceCategory.gi#L622

**Comment by zickgraf** [comment]
"before" would be possible using the following line instead of line 35 in the makefile:
```bash
grep -RE "[^ []  +[^#]" gap/*.gi && echo "Duplicate spaces found" && exit 1 || exit 0
```

However, in general I'm a bit hesitant when relaxing spacing rules, as that always implies that in other situations things are not detected, for example
```
Display( "Hello World" );  # oops, one additional space before the comment
```
would of course not be detected anymore.

If we are sure that your use-case is more important than detecting the example above, I can change the `grep` command.

**Comment by mohamed-barakat** [comment]
I would at least like to have the freedom to choose which kind of check is suitable for my needs or to disable whitespace entirely from the ci-test, in particular, it would be nice if the makefile entry ci-test is customizable.

**Comment by zickgraf** [comment]
There already exists `tests_only_basic: true`, which disables `test-spacing` and `test-doc`. Is this sufficient or would you like to have a more granular control? In the latter case I would suggest an exclude list (i.e., one can give a list of tests which should NOT run).
